language: node_js
node_js:
- "stable"
cache: npm
script: 'true'
before_script:
- npm install
deploy:
  provider: heroku:git
  api_key: d64ad810-1521-4f2a-95e4-4dd4b99f85a4
  app: tasktrufla
  skip_cleanup: true
  email: false
  on:
      branch: master
